[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints = {mainnet = "https://eth-mainnet.g.alchemy.com/v2/S7FGzEEsfVR6BassdzCaK8PLJXl53ZTo"}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config